apiVersion: v1
kind: Service
metadata:
  name: play-rest-test-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: 9000
    protocol: TCP
  selector:
    app: play-rest-test
  type: NodePort
